- scripts/make_report.py
Sorted uniq known genes, remove "--" separator.
> change knowngenes for BND type

- scripts/FilterManta.pl
- scripts/ichorToVCF.pl
Update from Dave's local git repo
> Update two scripts to be same as the ones under Dave local git repo

- Dockerfile
> More update

- scripts/local_launch_chromoseq.pl
> Update launcher script

- scripts/make_report.py
Refer to https://jira.ris.wustl.edu/browse/CI-515.
> Report change

- Chromoseq.wdl
- inputs.local.json
- scripts/FilterManta.pl
- scripts/ichorToVCF.pl
- scripts/make_report.py
Refer to https://jira.ris.wustl.edu/browse/CI-520
> More updates from Dave and me

- Chromoseq.wdl
- scripts/FilterManta.pl
These changes are needed for compute1 compatibility.
> Compute1 compatible

- Chromoseq.wdl
Fix the path of make_report.py.
> fix path of make_report.py

- Chromoseq.wdl
Fix hardcoded queue name: research-hpc in run_manta task.
> Fix hardcoded queue name

- Chromoseq.wdl
- inputs.local.json
So dragen command needs to be run locally. All inputs and outputs need to be placed under "/staging/runs" local SSD drive (6TB) on dragen node before the dragen command runs.
> Set up local dragen run

- Chromoseq.wdl
- inputs.local.json
- scripts/launcher.pl
- scripts/make_report.py
1. Sample exceptions are included in input sample spreadsheet and need to be added to the final report.
2. Use local dragen docker registry image.
3. Use "pathology" queue.
> Add sample exceptions to final report

- Chromoseq.wdl
Add the task of report json to Chromoseq.wdl as requested via https://jira.wustl.edu/browse/CI-575
> Add report JSON

- scripts/launcher.pl
For now the index needs to be 10-base strictly. Add error-checking code.
> Index needs to be 10-base long with no other weird characters

- scripts/launcher.pl
> Gender has to be either male or female

- scripts/launcher.pl
Sometimes expect 8-base indexes
> Allow 8-base index

- inputs.analysis.json
- inputs.json
Use registry.gsc.wustl.edu/mgi-cle/chromoseq:v1.1
> Local docker registry version update

- Chromoseq.wdl
Refer to https://jira.wustl.edu/browse/CI-682.
> Move dragen demux_fastq out of local staging drive and add "--gc-metrics-enable=true" to dragen align command

- scripts/make_report.py
This change also resolves syntax warning from python3 compiler.
> Use != and == for literal comparison

- Chromoseq.wdl
- ChromoseqAnalysis.wdl
- inputs.analysis.json
- inputs.json
updated to use new Dragen 4.0 parameters that we will eventually want to use, but will keep all other current aspects of chromoseq.
> updated dragen align command

- Chromoseq.wdl
> Replace staging path with storage1 path for POPAllele file

- inputs.json
Update json with upcoming newly upgraded dragen-2 queue (replacing duncavagee queue)
> Update json with the newly upgraded dragen-2 queue
